name: Publish Server

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to push branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Extract version from tag
        id: extract_version
        uses: damienaicheh/extract-version-from-tag-action@v1.1.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Run Tests
        if: job.status == 'success'
        run: |
          export GRADLE_USER_HOME=$(pwd)/.gradle
          chmod +x ./gradlew
          ./gradlew server:test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bring:${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}

      - name: Install and configure Koyeb CLI
        uses: koyeb-community/install-koyeb-cli@v2
        with:
          api_token: "${{ secrets.KOYEB_TOKEN }}"
          github_token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Deploy
        run: koyeb services update ${{ secrets.SERVICE_ID }} --docker ${{ secrets.DOCKER_USERNAME }}/bring:${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}